---@class BuffWatcher_AuraGroupFixedSettings
---@field friendlyName string
---@field includeBuffsAndCasts boolean
---@field includeDebuffs boolean
---@field isHostile boolean
---@field frameType FrameTypes
---@field icon integer
---@field selfPoint string
---@field anchorPoint string
---@field xOffset integer
---@field yOffset integer
BuffWatcher_AuraGroupFixedSettings = {}
