---@class BuffWatcher_AuraGroupUserSettings
---@field showUnlistedAuras BuffWatcher_ShowUnlistedType
---@field showDispelType boolean
---@field useDefaultIconSize boolean
---@field customIconSize number
---@field growDirection BuffWatcher_GrowDirection
---@field unlistedRowCount integer
---@field useDefaultUnlistedMultiplier boolean
---@field customUnlistedMultiplier number
---@field xOffset integer
---@field yOffset integer
---@field selfPoint string
---@field anchorPoint string
BuffWatcher_AuraGroupUserSettings = {}